

jobs:
  include:
    - stage: build
      language: node_js
      before_script:
        - npm install axios
      script:
        - npm run build
    - stage: percy
      language: ruby
      before_script:
        - gem install percy-cli
      script:
        - percy snapshot ./dist/ --enable_javascript